# Site settings
title: Tingyuan Luan
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "tyLuan|Make it Different"  
baseurl: ""
url: "http://tyluan.github.io"  

# About/contact
owner: 
  name: "栾婷媛"
  email: luantingyuan@126.com
  bio: ""

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: tyluan
weibo_username: 婷媛-yuanyuanluan
facebook_username:
zhihu_username: 栾媛媛

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "hanson"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : tyluan
  duoshuo :
    short_name : tyluan
  disqus :
      short_name : tyluan
# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
